#! /usr/bin/perl -w

if ( $#ARGV < 0 ){ print"
PROGRAM NAME:  CNOTEED  EDIT 20170610T140840Z
  Call: cnoteed tag
  Purpose: find the cruise note file and edit.
  where
    tag is a partial name of a file in the cruise folder, e.g. \'prp\'
    or tag is type grep, e.g. \"p.p\"
 e.g. cnoteed marcus
";
exit;
}

$tag = shift();
$npath = "~/Dropbox/cruises-ships";

@d = `find $npath -iname "*$tag*notes*.txt" -print`;
if( $#d > 0 ) {
	print"multiple results\n";
	$i=0;
	foreach(@d){
		chomp($fl=$d[$i]); 
		print"     $i  $fl\n";
		$i++;
	}
	print"SELECT ONE: ";
	chomp($i = <STDIN>);
	if( length($i) == 1){
		chomp($fl = $d[$i]);
	} else {exit}
} elsif ( $#d < 0 ) {
	print"No note match\n";
	@d = `find $npath -d 1 -iname *$tag* -print`;
	if($#d<0){
		print"No cruise with this name. Exit.\n";
		exit 1;
	}
	chomp($d[0]);
	$fl=sprintf"%s/%s_notes.txt",$d[0],$tag;
	print"touch $fl\n";
	system "touch $fl";
} else {
	chomp($fl = $d[0]);
}
print"fl = $fl\n";

$str= 'date -u "+%n========== %a %Y %m %d %H %M %S Z =================%n"';
system "$str >> \"$fl\"";
system "open -a /Applications/BBEdit.app \"$fl\"";
