#!/usr/bin/perl -X
#CALL:
#   FindUSBPort   =>> finds COM1
#   FindUSBPort 1 =>> finds COM1
#   FindUSBPort 2 =>> finds COM2 if available
# returns nothing otherwise
 
#@w = `ls /dev/tty*PL* 2>/dev/null`;
@w = `ls /dev/tty*usb* 2>/dev/null`;
@x = `ls /dev/tty*USB* 2>/dev/null`;
@w=(@w,@x);
if ( $#w < 0 ){exit 1}
if( $#ARGV>=0 && $ARGV[0]==2 && $#w <=0) {print""; exit 0}
if( $#ARGV>=0 && $ARGV[0]==2 && $#w >0) { 
	chomp($w[1]);
	print"$w[1]";
}else {
	chomp($w[0]);
	print"$w[0]";
}

exit 0;
